export interface Suggestion {
  value: string;
  unrestricted_value: string;
  data: {
    postal_code: null | string;
    country: string;
    country_iso_code: string;
    federal_district: null | string;
    region_fias_id: string;
    region_kladr_id: string;
    region_iso_code: string;
    region_with_type: string;
    region_type: string;
    region_type_full: string;
    region: string;
    area_fias_id: null | string;
    area_kladr_id: null | string;
    area_with_type: null | string;
    area_type: null | string;
    area_type_full: null | string;
    area: null | string;
    city_fias_id: string;
    city_kladr_id: string;
    city_with_type: string;
    city_type: string;
    city_type_full: string;
    city: string;
    city_area: null | string;
    city_district_fias_id: null | string;
    city_district_kladr_id: null | string;
    city_district_with_type: null | string;
    city_district_type: null | string;
    city_district_type_full: null | string;
    city_district: null | string;
    settlement_fias_id: null | string;
    settlement_kladr_id: null | string;
    settlement_with_type: null | string;
    settlement_type: null | string;
    settlement_type_full: null | string;
    settlement: null | string;
    street_fias_id: string;
    street_kladr_id: string;
    street_with_type: string;
    street_type: string;
    street_type_full: string;
    street: string;
    stead_fias_id: null | string;
    stead_cadnum: null | string;
    stead_type: null | string;
    stead_type_full: null | string;
    stead: null | string;
    house_fias_id: null | string;
    house_kladr_id: null | string;
    house_cadnum: null | string;
    house_type: null | string;
    house_type_full: null | string;
    house: null | string;
    block_type: null | string;
    block_type_full: null | string;
    block: null | string;
    entrance: null | string;
    floor: null | string;
    flat_fias_id: null | string;
    flat_cadnum: null | string;
    flat_type: null | string;
    flat_type_full: null | string;
    flat: null | string;
    flat_area: null | string;
    square_meter_price: null | string;
    flat_price: null | string;
    room_fias_id: null | string;
    room_cadnum: null | string;
    room_type: null | string;
    room_type_full: null | string;
    room: null | string;
    postal_box: null | string;
    fias_id: string;
    fias_code: null | string;
    fias_level: string;
    fias_actuality_state: string;
    kladr_id: string;
    geoname_id: string;
    capital_marker: string;
    okato: string;
    oktmo: string;
    tax_office: string;
    tax_office_legal: string;
    timezone: null | string;
    geo_lat: string;
    geo_lon: string;
    beltway_hit: null | string;
    beltway_distance: null | string;
    metro: null | string;
    divisions: null | string;
    qc_geo: 2;
    qc_complete: null | string;
    qc_house: null | string;
    history_values: string[];
    unparsed_parts: null | string;
    source: null | string;
    qc: null | string;
  };
}

export interface AddressSchema {
  suggestions?: { suggestions: Suggestion[] };
  addressQuery?: string;
  isLoading?: boolean;
  error?: string;
  isSuggestionEmpty?: boolean;
}
